./main.exe DY_Full_1 -1 &> logDY1.txt & 
./main.exe DY_Full_2 -1 &> logDY2.txt & 
./main.exe DY_Full_3 -1 &> logDY3.txt & 
./main.exe DY_Full_4 -1 &> logDY4.txt & 
./main.exe DY_Full_5 -1 &> logDY5.txt & 
./main.exe DY_Full_6 -1 &> logDY6.txt & 
./main.exe DY_Full_7 -1 &> logDY7.txt & 
./main.exe DY_Full_8 -1 &> logDY8.txt & 
./main.exe DY_Full_9 -1 &> logDY9.txt & 
./main.exe DY_Full_10 -1 &> logDY10.txt & 
./main.exe DY_Full_11 -1 &> logDY11.txt & 
./main.exe DY_Full_12 -1 &> logDY12.txt & 
./main.exe DY_Full_13 -1 &> logDY13.txt & 
#./main.exe DY_Full_14 -1 &> logDY14.txt & 
./main.exe DY_Full_15 -1 &> logDY15.txt & 
./main.exe DY_Full_16 -1 &> logDY16.txt & 
./main.exe DY_Full_17 -1 &> logDY17.txt & 
./main.exe DY_Full_18 -1 &> logDY18.txt & 
./main.exe DY_Full_19 -1 &> logDY19.txt & 
